In [49]:
#MNIST Reservoir                         #07/16/2021
import reservoirpy as rpy

from reservoirpy.nodes import Reservoir, Ridge

reservoir = Reservoir(100, lr=0.5, sr=0.9)
readout = Ridge(ridge=1e-7) #Ridge is the readout lyaer: uses linear regression

esn_model = reservoir >> readout #This connects the ridge node to the reservoir



In [50]:
import numpy
import matplotlib.pyplot
%matplotlib inline

#read in training data
tr_data_file = open(r"/Users/niharkoppolu/Desktop/Number_Detection_Project/mnist_data_set/mnist_train.csv")
tr_data_list = tr_data_file.readlines()
tr_data_file.close()


train_length = len(tr_data_list)

X_training_inputs = numpy.empty((train_length, 784))
Y_training_ans = numpy.empty(train_length)
index = 0


for record in tr_data_list:

        #convert test data from list off comma sep. vals to array of floats
        all_values = record.split(',')
        all_values = numpy.asfarray(all_values)

        #rescale data from 0 - 255 to range btw 0 - 0.99
        X_training_inputs[index] = (all_values[1:] / 255.0 * 0.99) + 0.01
        Y_training_ans[index] = all_values[0]#cast all training answers to ints

        index += 1
        pass



#USED TO TEST IF CORRECT VALUE IS BEING ADDED TO ARRAY
print("\n\nValue held in ans:\n", Y_training_ans[0])
print("\nX[0]:", X_training_inputs[:200])
"""
check_val = tr_data_list[0]
check_val = check_val.split(',')
image_array = numpy.asfarray(check_val[1:]).reshape((28,28))
matplotlib.pyplot.imshow(image_array, cmap='Greys', interpolation='None')
"""       



Value held in ans:
 5.0

X[0]: [[0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 ...
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]]


"\ncheck_val = tr_data_list[0]\ncheck_val = check_val.split(',')\nimage_array = numpy.asfarray(check_val[1:]).reshape((28,28))\nmatplotlib.pyplot.imshow(image_array, cmap='Greys', interpolation='None')\n"

In [51]:
train_states = reservoir.run(X_training_inputs, reset=True) #Putting input values into higher dimensional space

readout = Ridge(ridge=1e-7)
readout = readout.fit(train_states, Y_training_ans) #Training the readout layer. Warm-up discards first 10 timestep values

Running Reservoir-15: 100%|██████████| 60000/60000 [00:03<00:00, 17727.05it/s]


ValueError: shapes (60000,1) and (60000,101) not aligned: 1 (dim 1) != 60000 (dim 0)

In [ ]:
#Read in Test Data
#read in TEST data
test_data_file = open(r"/Users/niharkoppolu/Desktop/Number_Detection_Project/mnist_data_set/mnist_test.csv")
test_data_list = test_data_file.readlines()
test_data_file.close()

test_length = 10

test_inputs = numpy.empty((train_length, 784))
correct_answers = numpy.empty(train_length)

for i in test_length:
    all_testsets = test_data_list[i].split(',')
    all_testsets = numpy.asfarray(all_testsets)

    #copying in test inputs
    test_inputs[i] = (all_testsets[1:] / 255.0 * 0.99) + 0.01
    #copying in test answers
    correct_answers[i] = int(all_testsets[0])
    pass

TypeError: 'int' object is not iterable

In [ ]:
#Run Model and Display scorecard

scorecard = 0
i = 0

while i < 10:
    Pred_answer = esn_model.run(test_inputs[i])
    #Pred_answer = int(Pred_answer)
    print("\n\nCorrect Ans:", correct_answers[i])
    print("\tPredicted Ans:", Pred_answer)
    #check if pred val matches correct answer
    if correct_answers[i] == Pred_answer:
        scorecard += 1
        pass
    i += 1
pass

performance = scorecard/test_length

print("\n\nFinal performance:", performance)




    

Running Model-4: 100%|██████████| 1/1 [00:00<00:00, 1422.28it/s]



Correct Ans: 1.0
	Predicted Ans: [[3.2046111 3.2046111 3.2046111 3.2046111 3.2046111 3.2046111 3.2046111
  3.2046111 3.2046111 3.2046111]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()